USE MinistryPlatform
GO

DECLARE @Group_Type_ID AS INT = 26

SET IDENTITY_INSERT Groups ON

INSERT INTO [Groups]([Group_ID],[Group_Name],[Group_Type_ID],[Ministry_ID],[Congregation_ID],[Primary_Contact],[Description],[Start_Date],[End_Date],[Target_Size],[Parent_Group],[Priority_ID],[Enable_Waiting_List],[Small_Group_Information],[Offsite_Meeting_Address],[Group_Is_Full],[Available_Online],[Life_Stage_ID],[Group_Focus_ID],[Meeting_Time],[Meeting_Day_ID],[Descended_From],[Reason_Ended],[Domain_ID],[Check_in_Information],[Secure_Check-in],[Suppress_Nametag],[Suppress_Care_Note],[On_Classroom_Manager],[Promotion_Information],[Promote_to_Group],[Age_in_Months_to_Promote],[Promote_Weekly],[__ExternalGroupID],[__ExternalParentGroupID],[__IsPublic],[__ISBlogEnabled],[__ISWebEnabled],[Group_Notes],[Sign_Up_To_Serve],[Deadline_Passed_Message_ID],[Notifications],[Send_Attendance_Notification],[Send_Service_Notification],[Child_Care_Available],[Meeting_Frequency_ID],[Meeting_Duration_ID],[Required_Book],[Online_RSVP_Minimum_Age],[Enable_Discussion],[Small_Group_Information_2],[Remaining_Capacity])
VALUES(166570,'Undivided | Oakley | Summer 2016 | Holding Group',@Group_Type_ID,8,1,7592977,'This is the Crossroads Undivided Oakley holding group, which contains community members who need to be placed into Undivided Groups',CAST('20160615 00:00:00.000' as DATETIME),CAST('20160915 00:00:00.000' as DATETIME),NULL,NULL,NULL,0,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

INSERT INTO [Groups]([Group_ID],[Group_Name],[Group_Type_ID],[Ministry_ID],[Congregation_ID],[Primary_Contact],[Description],[Start_Date],[End_Date],[Target_Size],[Parent_Group],[Priority_ID],[Enable_Waiting_List],[Small_Group_Information],[Offsite_Meeting_Address],[Group_Is_Full],[Available_Online],[Life_Stage_ID],[Group_Focus_ID],[Meeting_Time],[Meeting_Day_ID],[Descended_From],[Reason_Ended],[Domain_ID],[Check_in_Information],[Secure_Check-in],[Suppress_Nametag],[Suppress_Care_Note],[On_Classroom_Manager],[Promotion_Information],[Promote_to_Group],[Age_in_Months_to_Promote],[Promote_Weekly],[__ExternalGroupID],[__ExternalParentGroupID],[__IsPublic],[__ISBlogEnabled],[__ISWebEnabled],[Group_Notes],[Sign_Up_To_Serve],[Deadline_Passed_Message_ID],[Notifications],[Send_Attendance_Notification],[Send_Service_Notification],[Child_Care_Available],[Meeting_Frequency_ID],[Meeting_Duration_ID],[Required_Book],[Online_RSVP_Minimum_Age],[Enable_Discussion],[Small_Group_Information_2],[Remaining_Capacity])
VALUES(166569,'Undivided | Mason | Summer 2016 | Holding Group',@Group_Type_ID,8,6,7592977,'This is the Crossroads Undivided Mason holding group, which contains community members who need to be placed into Undivided Groups',CAST('20160615 00:00:00.000' as DATETIME),CAST('20160915 00:00:00.000' as DATETIME),NULL,NULL,NULL,0,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

INSERT INTO [Groups]([Group_ID],[Group_Name],[Group_Type_ID],[Ministry_ID],[Congregation_ID],[Primary_Contact],[Description],[Start_Date],[End_Date],[Target_Size],[Parent_Group],[Priority_ID],[Enable_Waiting_List],[Small_Group_Information],[Offsite_Meeting_Address],[Group_Is_Full],[Available_Online],[Life_Stage_ID],[Group_Focus_ID],[Meeting_Time],[Meeting_Day_ID],[Descended_From],[Reason_Ended],[Domain_ID],[Check_in_Information],[Secure_Check-in],[Suppress_Nametag],[Suppress_Care_Note],[On_Classroom_Manager],[Promotion_Information],[Promote_to_Group],[Age_in_Months_to_Promote],[Promote_Weekly],[__ExternalGroupID],[__ExternalParentGroupID],[__IsPublic],[__ISBlogEnabled],[__ISWebEnabled],[Group_Notes],[Sign_Up_To_Serve],[Deadline_Passed_Message_ID],[Notifications],[Send_Attendance_Notification],[Send_Service_Notification],[Child_Care_Available],[Meeting_Frequency_ID],[Meeting_Duration_ID],[Required_Book],[Online_RSVP_Minimum_Age],[Enable_Discussion],[Small_Group_Information_2],[Remaining_Capacity])
VALUES(166568,'Undivided | Florence | Summer 2016 | Holding Group',@Group_Type_ID,8,7,7592977,'This is the Crossroads Undivided Florence holding group, which contains community members who need to be placed into Undivided Groups',CAST('20160615 00:00:00.000' as DATETIME),CAST('20160915 00:00:00.000' as DATETIME),NULL,NULL,NULL,0,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

INSERT INTO [Groups]([Group_ID],[Group_Name],[Group_Type_ID],[Ministry_ID],[Congregation_ID],[Primary_Contact],[Description],[Start_Date],[End_Date],[Target_Size],[Parent_Group],[Priority_ID],[Enable_Waiting_List],[Small_Group_Information],[Offsite_Meeting_Address],[Group_Is_Full],[Available_Online],[Life_Stage_ID],[Group_Focus_ID],[Meeting_Time],[Meeting_Day_ID],[Descended_From],[Reason_Ended],[Domain_ID],[Check_in_Information],[Secure_Check-in],[Suppress_Nametag],[Suppress_Care_Note],[On_Classroom_Manager],[Promotion_Information],[Promote_to_Group],[Age_in_Months_to_Promote],[Promote_Weekly],[__ExternalGroupID],[__ExternalParentGroupID],[__IsPublic],[__ISBlogEnabled],[__ISWebEnabled],[Group_Notes],[Sign_Up_To_Serve],[Deadline_Passed_Message_ID],[Notifications],[Send_Attendance_Notification],[Send_Service_Notification],[Child_Care_Available],[Meeting_Frequency_ID],[Meeting_Duration_ID],[Required_Book],[Online_RSVP_Minimum_Age],[Enable_Discussion],[Small_Group_Information_2],[Remaining_Capacity])
VALUES(166567,'Undivided | West Side | Summer 2016 | Holding Group',@Group_Type_ID,8,8,7592977,'This is the Crossroads Undivided West Side holding group, which contains community members who need to be placed into Undivided Groups',CAST('20160615 00:00:00.000' as DATETIME),CAST('20160915 00:00:00.000' as DATETIME),NULL,NULL,NULL,0,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

SET IDENTITY_INSERT Groups OFF
