USE MinistryPlatform
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'Event_Participants' AND COLUMN_NAME = 'End_Date')
BEGIN
	ALTER TABLE dbo.Event_Participants ADD End_Date DATETIME NULL;
END
