USE [MinistryPlatform]
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

IF NOT EXISTS (SELECT * FROM sys.columns WHERE Name = N'Requires_Active_Attribute' AND Object_ID = Object_ID(N'Attribute_Categories'))
BEGIN
ALTER TABLE [dbo].[Attribute_Categories]
ADD Requires_Active_Attribute BIT NOT NULL DEFAULT(0),
ADD Example_Text NVARCHAR(155) NULL
END