USE [MinistryPlatform]
GO

IF NOT EXISTS (SELECT * FROM [dbo].[cr_Other_Organizations]
		WHERE Other_Organization IN
		('4 Corners',
		'4 Corners Church',
		'7 Hills Church',
		'Abundant Life Faith Fellowship',
		'Alexandria UMC',
		'Ambassador''s Pointe East',
		'Anderson Hills United Methodist',
		'Anderson Hills United Methodist Church',
		'APEX',
		'Asbury College',
		'At. Johns Unitarian',
		'Bellarmine',
		'Bellermine Chapel at Xavier University',
		'Bethel Cincinnati',
		'Bright Christian Church',
		'CCM',
		'Center Pointe Christian Church',
		'Christ Church at Mason',
		'Christ Church Glendale',
		'Christ the King',
		'Christ''s Church at Mason',
		'Christian Life Center',
		'Christian Life Center - Huber Hgts Oh',
		'Church Of The Living God',
		'Cincinnati Chinese Church',
		'City on a Hill',
		'College Hill Presbyterian',
		'College-Conservatory of Music',
		'Community Fellowship',
		'Compass Community Church',
		'Connect Christian Church',
		'Cornerstone Missionary Baptists',
		'Countryside Church of the Nazarene',
		'Covenant First Presbyterian',
		'Dearborn Hills UMC',
		'Deleware Church of Christ',
		'Disciples of Christmas Christian Fellowship',
		'Dry Ridge Christian Church',
		'Faith Community Church',
		'Fellowship of Praise',
		'First Baptist Church Cold Spring',
		'First Christian Church of Columbus',
		'First Church New Knoxville',
		'First Church of Christ',
		'First Church of Christ Burlington',
		'First Church of Christ Union',
		'First Presbyterian Church of Fort Thomas',
		'Florence Baptist Church',
		'Four Corners',
		'Four Corners West Chester',
		'Friendship UMC',
		'Gaines United Methodist',
		'Good Shephard Catholic Church',
		'Good Shepherd Lutheran',
		'Grace Bible Presbyterian Church',
		'Grace Covenant Church',
		'Grace Fellowship Church',
		'Greater Bethlehem Temple Apostolic Church',
		'Hartwell United Methodist',
		'Heartland Church',
		'Heritage Presbyterian Church',
		'Hickory Grove Baptist Church',
		'Holy Trinity Church',
		'Horizon Community Church',
		'Immaculate Heart of Mary',
		'Immanuel Presbyterian church',
		'Immanuel United Methodist',
		'Inspirational Baptist Church',
		'John Wesley United Methodist',
		'Lakeside Christian',
		'Landmark',
		'Lebanon United Methodist',
		'Lewistown-trinity United Methodist Church (Lewistown, Ohio 43333)',
		'Liberty Heights',
		'Life Change Church',
		'Lifespring',
		'Light of the World',
		'Lynchburg Church of Christ',
		'Maple Ave Church of God',
		'Mariemont Church',
		'Marriott Hotels of Greater Cincinnati',
		'Mary Queen of Heaven',
		'Mary Queen of Heaven',
		'Mason Vinyard',
		'Milford First United Methodist',
		'Missio Dei Church',
		'Montgomery Community Church',
		'Montgomery Community Church',
		'Mosaic Cincinnati',
		'Mt Auburn Presbyterian Church',
		'Mt Zion Baptist Woodlawn',
		'Mt. Auburn Presbyterian Church',
		'New Bethel Baptist Church',
		'New City Presbyterian Church',
		'New Life Fellowship',
		'North Star Community Church',
		'Northern Hills Bible Chapel',
		'Northview Christian Church',
		'Oasis Nashville, TN',
		'One Hope Community Church / Welcome / Welcome',
		'Our Lady of the Rosary Parish',
		'Our Lady of the Visitation Parish',
		'Owensville United Methodist Church',
		'Parkside Christian',
		'Peoples Church',
		'Prince of Peace',
		'Quinn Chapel AME Church',
		'Redemption Bible Church',
		'Revival Center Ministries',
		'River of Life',
		'Rivers Crossing Community Church',
		'Rockdale Temple',
		'Saint Mary of the Assumption Parish',
		'Saint Matthew',
		'Saint Monica Saint George',
		'Saint Therese Church',
		'Saint Xavier',
		'Sharonville United Method',
		'Solid Rock',
		'Southwest Church',
		'Summit Church of Christ',
		'Sycamore Presbyterian',
		'Sycamore Presbyterian Church',
		'The Church of Jesus Christ of Latter Day Saints',
		'Trinity Christian',
		'Tryed Stone New Beginning Church',
		'Urbancrest Baptist',
		'Vineyard Cincinnati',
		'White Oak Christian Church',
		'White Water Crossing',
		'Whitewater Crossing',
		'Xenia Nazarene',
		'Xenos Christian Fellowship',
		'Zion Global Minitries')
	 )
	BEGIN
		INSERT INTO [dbo].[cr_Other_Organizations]
           ([Other_Organization])
		VALUES
		 ('4 Corners'),
		 ('4 Corners Church'),
		 ('7 Hills Church'),
		 ('Abundant Life Faith Fellowship'),
		 ('Alexandria UMC'),
		 ('Ambassador''s Pointe East'),
		 ('Anderson Hills United Methodist'),
		 ('Anderson Hills United Methodist Church'),
		 ('APEX'),
		 ('Asbury College'),
		 ('At. Johns Unitarian'),
		 ('Bellarmine'),
		 ('Bellermine Chapel at Xavier University'),
		 ('Bethel Cincinnati'),
		 ('Bright Christian Church'),
		 ('CCM'),
		 ('Center Pointe Christian Church'),
		 ('Christ Church at Mason'),
		 ('Christ Church Glendale'),
		 ('Christ the King'),
		 ('Christ''s Church at Mason'),
		 ('Christian Life Center'),
		 ('Christian Life Center - Huber Hgts Oh'),
		 ('Church Of The Living God'),
		 ('Cincinnati Chinese Church'),
		 ('City on a Hill'),
		 ('College Hill Presbyterian'),
		 ('College-Conservatory of Music'),
		 ('Community Fellowship'),
		 ('Compass Community Church'),
		 ('Connect Christian Church'),
		 ('Cornerstone Missionary Baptists'),
		 ('Countryside Church of the Nazarene'),
		 ('Covenant First Presbyterian'),
		 ('Dearborn Hills UMC'),
		 ('Deleware Church of Christ'),
		 ('Disciples of Christmas Christian Fellowship'),
		 ('Dry Ridge Christian Church'),
		 ('Faith Community Church'),
		 ('Fellowship of Praise'),
		 ('First Baptist Church Cold Spring'),
		 ('First Christian Church of Columbus'),
		 ('First Church New Knoxville'),
		 ('First Church of Christ'),
		 ('First Church of Christ Burlington'),
		 ('First Church of Christ Union'),
		 ('First Presbyterian Church of Fort Thomas'),
		 ('Florence Baptist Church'),
		 ('Four Corners'),
		 ('Four Corners West Chester'),
		 ('Friendship UMC'),
		 ('Gaines United Methodist'),
		 ('Good Shephard Catholic Church'),
		 ('Good Shepherd Lutheran'),
		 ('Grace Bible Presbyterian Church'),
		 ('Grace Covenant Church'),
		 ('Grace Fellowship Church'),
		 ('Greater Bethlehem Temple Apostolic Church'),
		 ('Hartwell United Methodist'),
		 ('Heartland Church'),
		 ('Heritage Presbyterian Church'),
		 ('Hickory Grove Baptist Church'),
		 ('Holy Trinity Church'),
		 ('Horizon Community Church'),
		 ('Immaculate Heart of Mary'),
		 ('Immanuel Presbyterian church'),
		 ('Immanuel United Methodist'),
		 ('Inspirational Baptist Church'),
		 ('John Wesley United Methodist'),
		 ('Lakeside Christian'),
		 ('Landmark'),
		 ('Lebanon United Methodist'),
		 ('Lewistown-trinity United Methodist Church (Lewistown, Ohio 43333)'),
		 ('Liberty Heights'),
		 ('Life Change Church'),
		 ('Lifespring'),
		 ('Light of the World'),
		 ('Lynchburg Church of Christ'),
		 ('Maple Ave Church of God'),
		 ('Mariemont Church'),
		 ('Marriott Hotels of Greater Cincinnati'),
		 ('Mary Queen of Heaven'),
		 ('Mary Queen of Heaven'),
		 ('Mason Vinyard'),
		 ('Milford First United Methodist'),
		 ('Missio Dei Church'),
		 ('Montgomery Community Church'),
		 ('Montgomery Community Church'),
		 ('Mosaic Cincinnati'),
		 ('Mt Auburn Presbyterian Church'),
		 ('Mt Zion Baptist Woodlawn'),
		 ('Mt. Auburn Presbyterian Church'),
		 ('New Bethel Baptist Church'),
		 ('New City Presbyterian Church'),
		 ('New Life Fellowship'),
		 ('North Star Community Church'),
		 ('Northern Hills Bible Chapel'),
		 ('Northview Christian Church'),
		 ('Oasis Nashville, TN'),
		 ('One Hope Community Church / Welcome / Welcome'),
		 ('Our Lady of the Rosary Parish'),
		 ('Our Lady of the Visitation Parish'),
		 ('Owensville United Methodist Church'),
		 ('Parkside Christian'),
		 ('Peoples Church'),
		 ('Prince of Peace'),
		 ('Quinn Chapel AME Church'),
		 ('Redemption Bible Church'),
		 ('Revival Center Ministries'),
		 ('River of Life'),
		 ('Rivers Crossing Community Church'),
		 ('Rockdale Temple'),
		 ('Saint Mary of the Assumption Parish'),
		 ('Saint Matthew'),
		 ('Saint Monica Saint George'),
		 ('Saint Therese Church'),
		 ('Saint Xavier'),
		 ('Sharonville United Method'),
		 ('Solid Rock'),
		 ('Southwest Church'),
		 ('Summit Church of Christ'),
		 ('Sycamore Presbyterian'),
		 ('Sycamore Presbyterian Church'),
		 ('The Church of Jesus Christ of Latter Day Saints'),
		 ('Trinity Christian'),
		 ('Tryed Stone New Beginning Church'),
		 ('Urbancrest Baptist'),
		 ('Vineyard Cincinnati'),
		 ('White Oak Christian Church'),
		 ('White Water Crossing'),
		 ('Whitewater Crossing'),
		 ('Xenia Nazarene'),
		 ('Xenos Christian Fellowship'),
		 ('Zion Global Minitries')
	END
GO
