DBCC CHECKIDENT (Attribute_Types, reseed, 1000)
DBCC CHECKIDENT (Attribute_Categories, reseed, 1000)
DBCC CHECKIDENT (Attributes, reseed, 20000)
DBCC CHECKIDENT (dp_Pages, reseed, 1000)
DBCC CHECKIDENT (dp_Processes, reseed, 1000)
DBCC CHECKIDENT (dp_Sub_Pages, reseed, 1000)
DBCC CHECKIDENT (dp_Sub_Page_Views, reseed, 1000)
DBCC CHECKIDENT (dp_Reports, reseed, 1000)
DBCC CHECKIDENT (dp_Roles , reseed, 1000)
DBCC CHECKIDENT (dp_Tools , reseed, 600)