USE [MinistryPlatform]
GO


DELETE FROM RESPONSES WHERE OPPORTUNITY_ID IN (SELECT OPPORTUNITY_ID FROM OPPORTUNITIES WHERE Opportunity_Title like '(t+auto) Attack Shinra Mako reactor%');

DELETE FROM EVENT_PARTICIPANTS WHERE OPPORTUNITY_ID IN (SELECT OPPORTUNITY_ID FROM OPPORTUNITIES WHERE ADD_TO_GROUP IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t+auto) Avalanche'));

DELETE FROM EVENT_PARTICIPANTS WHERE GROUP_ID IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t+auto) Avalanche');

DELETE FROM GROUP_PARTICIPANTS WHERE GROUP_ID IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t+auto) Avalanche');

DELETE FROM EVENT_GROUPS WHERE GROUP_ID IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t+auto) Avalanche');

DELETE FROM OPPORTUNITIES WHERE ADD_TO_GROUP IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t+auto) Avalanche');

DELETE FROM GROUPS WHERE GROUP_NAME = '(t+auto) Avalanche';
