USE [MinistryPlatform]
GO


DELETE FROM RESPONSES WHERE OPPORTUNITY_ID IN (SELECT OPPORTUNITY_ID FROM OPPORTUNITIES WHERE Opportunity_Title like '(t) Kindergarten K213%');
DELETE FROM OPPORTUNITIES WHERE GROUP_ID IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t) KC Oakley Kindergarten');

DELETE FROM GROUP_PARTICIPANTS WHERE GROUP_ID IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t) KC Oakley Kindergarten');
DELETE FROM GROUPS WHERE GROUP_NAME = '(t) KC Oakley Kindergarten';
GO