USE [MinistryPlatform]
GO


DELETE FROM RESPONSES WHERE OPPORTUNITY_ID IN (SELECT OPPORTUNITY_ID FROM OPPORTUNITIES WHERE Opportunity_Title like '(t) Kindergarten K213%');

DELETE FROM EVENT_PARTICIPANTS WHERE OPPORTUNITY_ID IN (SELECT OPPORTUNITY_ID FROM OPPORTUNITIES WHERE ADD_TO_GROUP IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t) KC Oakley Kindergarten'));

DELETE FROM GROUP_PARTICIPANTS WHERE GROUP_ID IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t) KC Oakley Kindergarten');

DELETE FROM EVENT_GROUPS WHERE GROUP_ID IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t) KC Oakley Kindergarten');

DELETE FROM OPPORTUNITIES WHERE ADD_TO_GROUP IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t) KC Oakley Kindergarten');

DELETE FROM GROUPS WHERE GROUP_NAME = '(t) KC Oakley Kindergarten';
GO

DELETE FROM RESPONSES WHERE OPPORTUNITY_ID IN (SELECT OPPORTUNITY_ID FROM OPPORTUNITIES WHERE Opportunity_Title like '(t) KC Oakley Nursery%');

DELETE FROM EVENT_PARTICIPANTS WHERE OPPORTUNITY_ID IN (SELECT OPPORTUNITY_ID FROM OPPORTUNITIES WHERE ADD_TO_GROUP IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t) KC Oakley Nursery'));

DELETE FROM GROUP_PARTICIPANTS WHERE GROUP_ID IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t) KC Oakley Nursery');

DELETE FROM EVENT_GROUPS WHERE GROUP_ID IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t) KC Oakley Nursery');

DELETE FROM OPPORTUNITIES WHERE ADD_TO_GROUP IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t) KC Oakley Nursery');

DELETE FROM GROUPS WHERE GROUP_NAME = '(t) KC Oakley Nursery';
