USE [MinistryPlatform]
GO


DELETE FROM RESPONSES WHERE OPPORTUNITY_ID IN (SELECT OPPORTUNITY_ID FROM OPPORTUNITIES WHERE Opportunity_Title like '(t+auto) Guard Shinra Mako reactor%');

DELETE FROM EVENT_PARTICIPANTS WHERE OPPORTUNITY_ID IN (SELECT OPPORTUNITY_ID FROM OPPORTUNITIES WHERE ADD_TO_GROUP IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t+auto) Serve Shinra Electric Power Company'));

DELETE FROM GROUP_PARTICIPANTS WHERE GROUP_ID IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t+auto) Serve Shinra Electric Power Company');

DELETE FROM EVENT_GROUPS WHERE GROUP_ID IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t+auto) Serve Shinra Electric Power Company');

DELETE FROM OPPORTUNITIES WHERE ADD_TO_GROUP IN (SELECT GROUP_ID FROM GROUPS WHERE GROUP_NAME = '(t+auto) Serve Shinra Electric Power Company');

DELETE FROM GROUPS WHERE GROUP_NAME = '(t+auto) Serve Shinra Electric Power Company';
